<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Pokemon;

class PokemonSeeder extends Seeder
{
    public function run(): void
    {
        $pokemons = [
    [
        'name' => 'Bulbasaur',
        'element' => 'Land',
        'type' => 'Grass',
        'rarity' => 'Common',
        'level' => 5,
        'hp' => 45,
        'attack' => 49,
        'image' => 'bulbasaur.png',
        'description' => 'A seed Pokémon that carries a plant bulb on its back.',
    ],
    [
        'name' => 'Squirtle',
        'element' => 'Water',
        'type' => 'Water',
        'rarity' => 'Common',
        'level' => 5,
        'hp' => 44,
        'attack' => 48,
        'image' => 'squirtle.png',
        'description' => 'Turtle Pokémon that shoots water from its shell.',
    ],
    [
        'name' => 'Charmander',
        'element' => 'Land',
        'type' => 'Fire',
        'rarity' => 'Common',
        'level' => 5,
        'hp' => 39,
        'attack' => 52,
        'image' => 'charmander.png',
        'description' => 'A fire lizard Pokémon with a flame at the tip of its tail.',
    ],
    [
        'name' => 'Pidgey',
        'element' => 'Air',
        'type' => 'Flying',
        'rarity' => 'Common',
        'level' => 3,
        'hp' => 40,
        'attack' => 45,
        'image' => 'pidgey.png',
        'description' => 'A tiny bird Pokémon that is very docile.',
    ],
    [
        'name' => 'Rattata',
        'element' => 'Land',
        'type' => 'Normal',
        'rarity' => 'Common',
        'level' => 2,
        'hp' => 30,
        'attack' => 56,
        'image' => 'rattata.png',
        'description' => 'A small, fast rodent Pokémon with sharp fangs.',
    ],
    [
        'name' => 'Geodude',
        'element' => 'Land',
        'type' => 'Rock',
        'rarity' => 'Common',
        'level' => 7,
        'hp' => 50,
        'attack' => 80,
        'image' => 'geodude.png',
        'description' => 'A rock Pokémon that is often found in fields and mountains.',
    ],
    [
        'name' => 'Magikarp',
        'element' => 'Water',
        'type' => 'Water',
        'rarity' => 'Common',
        'level' => 2,
        'hp' => 20,
        'attack' => 10,
        'image' => 'magikarp.png',
        'description' => 'A weak and pathetic Pokémon that can barely swim.',
    ],
    [
        'name' => 'Zubat',
        'element' => 'Air',
        'type' => 'Poison',
        'rarity' => 'Common',
        'level' => 4,
        'hp' => 40,
        'attack' => 45,
        'image' => 'zubat.png',
        'description' => 'A bat Pokémon that emits ultrasonic cries while it flies.',
    ],
    [
        'name' => 'Oddish',
        'element' => 'Land',
        'type' => 'Grass',
        'rarity' => 'Common',
        'level' => 6,
        'hp' => 45,
        'attack' => 50,
        'image' => 'oddish.png',
        'description' => 'A weed Pokémon that buries itself in the ground during the day.',
    ],
    [
        'name' => 'Psyduck',
        'element' => 'Water',
        'type' => 'Water',
        'rarity' => 'Common',
        'level' => 6,
        'hp' => 50,
        'attack' => 52,
        'image' => 'psyduck.png',
        'description' => 'A duck Pokémon that suffers from constant headaches.',
    ],
    [
        'name' => 'Mewtwo',
        'element' => 'Land',
        'type' => 'Psychic',
        'rarity' => 'Legendary',
        'level' => 70,
        'hp' => 106,
        'attack' => 110,
        'image' => 'mewtwo.png',
        'description' => 'A legendary psychic Pokémon created by genetic manipulation.',
    ],
    [
        'name' => 'Zapdos',
        'element' => 'Air',
        'type' => 'Electric',
        'rarity' => 'Legendary',
        'level' => 50,
        'hp' => 90,
        'attack' => 90,
        'image' => 'zapdos.png',
        'description' => 'A legendary bird Pokémon that controls electricity.',
    ],
    [
        'name' => 'Articuno',
        'element' => 'Air',
        'type' => 'Ice',
        'rarity' => 'Legendary',
        'level' => 50,
        'hp' => 90,
        'attack' => 85,
        'image' => 'articuno.png',
        'description' => 'A legendary bird Pokémon that controls ice.',
    ],
    [
        'name' => 'Moltres',
        'element' => 'Air',
        'type' => 'Fire',
        'rarity' => 'Legendary',
        'level' => 50,
        'hp' => 90,
        'attack' => 100,
        'image' => 'moltres.png',
        'description' => 'A legendary bird Pokémon that controls fire.',
    ],
    [
        'name' => 'Rayquaza',
        'element' => 'Air',
        'type' => 'Dragon',
        'rarity' => 'Legendary',
        'level' => 70,
        'hp' => 105,
        'attack' => 120,
        'image' => 'rayquaza.png',
        'description' => 'A legendary dragon Pokémon that lives in the ozone layer.',
    ],
    [
        'name' => 'Groudon',
        'element' => 'Land',
        'type' => 'Ground',
        'rarity' => 'Legendary',
        'level' => 70,
        'hp' => 100,
        'attack' => 150,
        'image' => 'groudon.png',
        'description' => 'A legendary Pokémon that brought land to the world.',
    ],
    [
        'name' => 'Kyogre',
        'element' => 'Water',
        'type' => 'Water',
        'rarity' => 'Legendary',
        'level' => 70,
        'hp' => 100,
        'attack' => 120,
        'image' => 'kyogre.png',
        'description' => 'A legendary Pokémon that brought water to the world.',
    ],
    [
        'name' => 'Lugia',
        'element' => 'Air',
        'type' => 'Psychic',
        'rarity' => 'Legendary',
        'level' => 70,
        'hp' => 106,
        'attack' => 90,
        'image' => 'lugia.png',
        'description' => 'A legendary Pokémon said to be the guardian of the seas.',
    ],
    [
        'name' => 'Ho-Oh',
        'element' => 'Air',
        'type' => 'Fire',
        'rarity' => 'Legendary',
        'level' => 70,
        'hp' => 106,
        'attack' => 130,
        'image' => 'hooh.png',
        'description' => 'A legendary Pokémon said to bring happiness to those who see it.',
    ],
    [
        'name' => 'Celebi',
        'element' => 'Land',
        'type' => 'Psychic',
        'rarity' => 'Legendary',
        'level' => 50,
        'hp' => 100,
        'attack' => 100,
        'image' => 'celebi.png',
        'description' => 'A mythical Pokémon that travels through time.',
    ],
];
        foreach ($pokemons as $poke) {
            Pokemon::create($poke);
        }
    }
}
